config/routes.rb
Site::Application.routes.draw do
  resources :articles, :only => [:index, :show]
  match '/code', :to => 'pages#code', :as => 'code', :via => :get
  match '/publications', :to => 'pages#publications', :as => 'publications', :via => :get
  root :to => 'articles#index', :via => :get
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :load_posts

  cattr_accessor :mtime
  cattr_accessor :articles

  def show
    @article = articles.select { |a| a[:id].to_s == params[:id].to_s }.first
  end

  def index
    @articles = articles
    respond_to do |format|
      format.atom
      format.html
    end
  end

protected

  def load_posts
    config = Site.configuration
    filename = ::Rails.root.join(config[:posts_dir], config[:posts_file])
    if mtime.blank? || File.mtime(filename) > mtime
      self.mtime = File.mtime(filename)
      self.articles = YAML::load(File.open(filename)).sort do |a, b|
        b[:time] <=> a[:time]
      end
    end
    articles
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.haml
- unless @articles.nil? or @articles.blank?
  - @articles.each do |article|
    %article.article
      %header.title
        %time.right-time{ :datetime => article[:time].iso8601, :title => article[:time].to_s(:post_full) }
          = time_ago_in_words(article[:time])
        %h3= article[:title]
        .clear-both
      %p.snippet
        = article[:snippet]
      .continue= link_to 'read full article &raquo;'.html_safe, article_path(article[:id])
- else
  There's nothing to see here. Please move along.

app/views/articles/show.html.haml
- if @article.nil?
  This post doesn't exist. Please try another
- else
  %article.article
    %header.title
      %h1= @article[:title]
      %time.time{ :datetime => @article[:time].iso8601, :title => @article[:time].to_s(:post_full) }
        = time_ago_in_words(@article[:time])

    -# Fix the caching problem in development
    - filename = ::Rails.root.join(Site.configuration[:posts_dir], @article[:file])
    - if Rails.env.development?
      - File.open(filename) do |file|
        = raw PandocRuby.convert(file.read)
    - else
      = render :file => filename

app/views/layouts/_nav.html.haml
#sidebar_button.sidebar-button ☰
%ul.vertical-list
  %li<>= link_to t('.home'), root_path
  %li<>= link_to t('.scrapbook'), 'http://scrapbook.srikanthak.name'
  %li<>= link_to t('.code'), code_path
  %li<>= link_to t('.publications'), publications_path
  %li<>= link_to t('.resume'), '/files/srikanth_resume.pdf'

app/views/layouts/application.html.haml
!!! 5
%html{html_attrs, 'xmlns:og' => 'http://opengraphprotocol.org/schema/'}
  %head
    %title= @title.present? ? t('.full_title', :title => @title) : t('.title')
    %meta{:name => "viewport", :content => "width=device-width" }
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = auto_discovery_link_tag(:atom, articles_path(:format => :atom))
  %body
    %header.top
      %aside#sidebar.sidebar= render :partial => 'layouts/nav'
      = link_to t('.title'), root_path, :class => 'logo'
      .subtitle
        Everything from cricket to programming.

    %section.main
      = yield
    %footer.bottom
      © 2005-2013 Srikanth Agaram

app/views/pages/code.html.haml
%article.article
  %header.title
    %h1 Code

  :markdown
    ### Current Projects

     - A system to automate the [building of e-books](http://github.com/aksrikanth/library-build-system/) in various formats from plain text files.
     - [This website](http://github.com/aksrikanth/site/) including the blogging engine.
     - My helper scripts and [configuration files](http://github.com/aksrikanth/settings/).

    ### Past Projects

     - [Wireless setup script](https://gist.github.com/aksrikanth/5073729) to fill the lack of good wireless configuration tools in Linux.
     - An [automated script](https://gist.github.com/aksrikanth/5073716) to backup DVD movies and encode them into the OGM format. Uses MPlayer and Ogm-tools to do the heavy lifting.

app/views/pages/publications.html.haml
%article.article
  %header.title
    %h1 Publications

  :markdown

     - Event Based Organization and Access of Digital Photos - US 2009/0319472 A1 filed April 2008 [PDF](/files/JainWestermannScherpAgaram-EventBasedOrganizationAndAccessOfDigitalPhotos.pdf)
     - Event-Centric Media Management in SPIE's 20th Annual Symposium Electronic Imaging Science and Technology 2008 [PDF](/files/ScherpAgaramJain-EventCentricMediaManagement.pdf)
     - Event-Centric Multimedia Data Management for Reconnaissance Mission Analysis and Reporting in Proc of the 14th annual ACM international conference on Multimedia 2006 [PDF](/files/WestermannAgaramGongJain-EventCentricMultimediaDataManagementforReconnaissanceMissionAnalysisandReporting.pdf)
     - Event Discovery in Multimedia Reconnaissance Data Using Spatio-Temporal Clustering in Proc of the AAAI Workshop on Event Extraction and Synthesis 2006 [PDF](/files/GongWestermannAgaramJain-EventDiscoveryInMultimediaReconnaissanceDataUsingSpatioTemporalClustering.pdf)
     - Application of Neural Networks to Security Analysis in Proc of National Systems Conference 2002, Hyderabad India